routes/web.php
<?php

use App\Http\Controllers\CosineSimilarityController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\ImportDocumentController;
use App\Models\Temp;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});

Route::group(['middleware'=>['auth:sanctum']], function(){
    Route::get('/cosinesimilarity',DashboardController::class)->name('cosinesimilarity');
    Route::post('/consinesimilarities', [CosineSimilarityController::class, 'check'])
    ->name('consinesimilarities.check');

    Route::resources([
        'documents' => DocumentController::class,
    ]);

    Route::get('/import-documents',ImportDocumentController::class)
    ->name('import-documents.store');
});

Route::get('/list-documents', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'documentAndQuery' => $payload['documentAndQuery'],
    ];
    return view('cosim.document', $data);
})->name('list-documents');

Route::get('/step-1', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
    ];
    return view('cosim.step-1', $data);
})->name('step-1');

Route::get('/step-2', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allFiltering' => $payload['allFiltering'],
    ];
    return view('cosim.step-2', $data);
})->name('step-2');

Route::get('/step-3', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allStemming' => $payload['allStemming'],
    ];
    return view('cosim.step-3', $data);
})->name('step-3');

Route::get('/step-4', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
        'terms' => $payload['terms'],
    ];
    return view('cosim.step-4', $data);
})->name('step-4');

Route::get('/step-5', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
        'sumCrossVector' => $payload['sumCrossVector'],
        'terms' => $payload['terms'],
    ];
    return view('cosim.step-5', $data);
})->name('step-5');

Route::get('/step-6', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
        'terms' => $payload['terms'],
        'sqrtCs' => $payload['sqrtCs'],
    ];
    return view('cosim.step-6', $data);
})->name('step-6');



Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return Inertia::render('Dashboard');
})->name('dashboard');

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title inertia>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        <!-- Scripts -->
        @routes
        <script src="{{ mix('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        @inertia

        @env ('local')
            <script src="http://localhost:3000/browser-sync/browser-sync-client.js"></script>
        @endenv
    </body>
</html>

resources/views/home.blade.php
@extends('master')

@section('content')
<div class="container">
    <br>
    <br>
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div style="color:red">{{$error}}</div>
        @endforeach
    @endif

    <div class="row">
        <div class="col-12">
            <form action="{{ route('consinesimilarities.check') }}" method="POST">
                @csrf
                @method('POST')
                <div class="form-group">
                    <label for="query">Cari Naskah</label>
                    <input type="text" class="form-control" name="query" placeholder="Masukkan kalimat" id="query">
                </div>
                <button type="submit" class="btn-sm btn-primary">Submit</button>
            </form>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-12">
            <h2>Naskah Khutbah</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                    <th>No</th>
                    <th>Judul</th>
                    <th>Option</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($documents as $document)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $document->title }}</td>
                            <td>
                                <a href="{{ route('documents.show', $document) }}" class="btn-sm btn-info">Detail</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
  </div>
@endsection

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
    @include('templates.header')
    <body>

        @include('templates.navbar')
        <div class="container-fluid">
            @include('templates.error')
            @yield('content')
        </div>

    </body>
</html>