routes/web.php
<?php

use App\Http\Controllers\CosineSimilarityController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\ImportDocumentController;
use App\Models\Temp;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});

Route::group(['middleware'=>['auth:sanctum']], function(){
    Route::get('/cosinesimilarity',DashboardController::class)->name('cosinesimilarity');
    Route::post('/consinesimilarities', [CosineSimilarityController::class, 'check'])
    ->name('consinesimilarities.check');

    Route::resources([
        'documents' => DocumentController::class,
    ]);

    Route::get('/import-documents',ImportDocumentController::class)
    ->name('import-documents.store');
});

Route::get('/list-documents', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'documentAndQuery' => $payload['documentAndQuery'],
    ];
    return view('cosim.document', $data);
})->name('list-documents');

Route::get('/step-1', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
    ];
    return view('cosim.step-1', $data);
})->name('step-1');

Route::get('/step-2', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allFiltering' => $payload['allFiltering'],
    ];
    return view('cosim.step-2', $data);
})->name('step-2');

Route::get('/step-3', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allStemming' => $payload['allStemming'],
    ];
    return view('cosim.step-3', $data);
})->name('step-3');

Route::get('/step-4', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
        'terms' => $payload['terms'],
    ];
    return view('cosim.step-4', $data);
})->name('step-4');

Route::get('/step-5', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
        'sumCrossVector' => $payload['sumCrossVector'],
        'terms' => $payload['terms'],
    ];
    return view('cosim.step-5', $data);
})->name('step-5');

Route::get('/step-6', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
        'terms' => $payload['terms'],
        'sqrtCs' => $payload['sqrtCs'],
    ];
    return view('cosim.step-6', $data);
})->name('step-6');



Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return Inertia::render('Dashboard');
})->name('dashboard');

app/Models/Document.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    use HasFactory;

    protected $table = 'documents';
    protected $fillable = [
        'title',
        'content',
    ];
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Document;
use App\Repositories\DocumentRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Throwable;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $r = new \App\Repositories\DocumentRepository();
        $data = [
            'documents' => $r->all(),
        ];
        return view('documents.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $validate = $this->validate($request, [
                'content'   => 'required',
                'title'     => 'required|string|max:250'
            ]);
            $s = new \App\Services\DocumentService();
            $s->store($validate);
            return redirect(route('documents.index'))->with('alert-success', 'Data created successfully');
        }catch(\Throwable $th){
            Log::error([
                get_class($this) . 'store' . json_encode($request->all()),
                'Message ' . $th->getMessage(),
                'On line ' . $th->getLine(),
            ]);
            return back()->with('alert', $th->getMessage())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
        //

        try{
            $data = [
                'document' => $document
            ];

            return view('documents.show', $data);
        }catch(Throwable $th){
            Log::error([
                'Message ' . $th->getMessage(),
                'On line ' . $th->getLine(),
                'On file ' . $th->getFile()
            ]);
            return back()->with('alert', $th->getMessage());
        }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Document $document)
    {
        try{
            $data = [
                'document' => $document
            ];

            return view('documents.edit', $data);
        }catch(Throwable $th){
            Log::error([
                'Message ' . $th->getMessage(),
                'On line ' . $th->getLine(),
                'On file ' . $th->getFile()
            ]);
            return back()->with('alert', $th->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Document $document)
    {
        try{
            $validate = $this->validate($request, [
                'title'     => 'required|string|max:255',
                'content'   => 'required'
            ]);
    
            $s = new \App\Services\DocumentService();
            $s->update($validate, $document->id);
            return redirect(route('documents.index'))->with('alert-success', 'Document successfully added');
        }catch(\Throwable $th){
            Log::error([
                get_class($this) . 'update with params ' . json_encode($request->all()),
                'Message ' . $th->getMessage(),
                'On line ' . $th->getLine(),
            ]);
            return back()->with('alert', $th->getMessage())->withInput();
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Document $document, DocumentRepository $documentRepository)
    {
        try{
            $documentRepository->delete($document->id);
            return redirect(route('documents.index'))->with('alert-success', 'Document successfully destroyed');
        }catch(\Throwable $th){
            Log::error([
                get_class($this) . 'destroy',
                'Message ' . $th->getMessage(),
                'On line ' . $th->getLine(),
            ]);
            return back()->with('alert', $th->getMessage())->withInput();
        }
    }
}

resources/views/documents/edit.blade.php
@extends('master')

@section('content')
<div class="container">
    <br>
    <br>
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div style="color:red">{{$error}}</div>
        @endforeach
    @endif

    <div class="row">
        <div class="col-12">
            <form action="{{ route('documents.update', $document) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="comment">Title</label>
                    <input type="text" class="form-control" name="title"
                    value="{{ old('title') ?? $document->title }}">
                </div>
                <div class="form-group">
                    <label for="comment">Document:</label>
                    <textarea class="form-control" name="content" rows="5" id="content">
                        {{ old('content') ?? $document->content }}
                    </textarea>
                </div>
                <button type="submit" class="btn-sm btn-primary">Submit</button>
            </form>
        </div>
    </div>
    <br>
  </div>
@endsection

resources/views/documents/index.blade.php
@extends('master')

@section('content')
<div class="container">
    <br>
    <br>
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div style="color:red">{{$error}}</div>
        @endforeach
    @endif

    <div class="row">
        <div class="col-12">
            <form action="{{ route('documents.store') }}" method="POST">
                @csrf
                @method('POST')
                <div class="form-group">
                    <label for="comment">Judul</label>
                    <input type="text" class="form-control" name="title"
                    value="{{ old('title') }}">
                </div>
                <div class="form-group">
                    <label for="comment">Isi Naskah:</label>
                    <textarea class="form-control" name="content" rows="5" id="content">
                        {{ old('content') }}
                    </textarea>
                </div>
                <button type="submit" class="btn-sm btn-primary">Submit</button>
            </form>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-12">
            <h2>Data Naskah</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                    <th>No</th>
                    <th>Judul</th>
                    <th>Option</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($documents as $document)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $document->title }}</td>
                            <td width="30%">
                                <a href="{{ route('documents.show', $document) }}" type="button" class="btn-sm btn-info">Detail</a>
                                <a href="{{ route('documents.edit', $document) }}" type="button" class="btn-sm btn-primary">Edit</a>
                                <form action="{{ route('documents.destroy', $document) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-sm btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
  </div>
@endsection

resources/views/documents/show.blade.php
@extends('master')

@section('content')
<div class="container">
    <br>
    <br>
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div style="color:red">{{$error}}</div>
        @endforeach
    @endif

    <div class="row">
        <div class="col-12">
            <h3>Detail Naskah</h3>
            <strong>
                {{ $document->title }}
            </strong>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            <h3>Isi Naskah</h3>
            {{ $document->content }}
        </div>
    </div>
    <br>
  </div>
@endsection