routes/web.php
<?php

use App\Http\Controllers\CosineSimilarityController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\ImportDocumentController;
use App\Models\Temp;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});

Route::group(['middleware'=>['auth:sanctum']], function(){
    Route::get('/cosinesimilarity',DashboardController::class)->name('cosinesimilarity');
    Route::post('/consinesimilarities', [CosineSimilarityController::class, 'check'])
    ->name('consinesimilarities.check');

    Route::resources([
        'documents' => DocumentController::class,
    ]);

    Route::get('/import-documents',ImportDocumentController::class)
    ->name('import-documents.store');
});

Route::get('/list-documents', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'documentAndQuery' => $payload['documentAndQuery'],
    ];
    return view('cosim.document', $data);
})->name('list-documents');

Route::get('/step-1', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
    ];
    return view('cosim.step-1', $data);
})->name('step-1');

Route::get('/step-2', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allFiltering' => $payload['allFiltering'],
    ];
    return view('cosim.step-2', $data);
})->name('step-2');

Route::get('/step-3', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allStemming' => $payload['allStemming'],
    ];
    return view('cosim.step-3', $data);
})->name('step-3');

Route::get('/step-4', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
        'terms' => $payload['terms'],
    ];
    return view('cosim.step-4', $data);
})->name('step-4');

Route::get('/step-5', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
        'sumCrossVector' => $payload['sumCrossVector'],
        'terms' => $payload['terms'],
    ];
    return view('cosim.step-5', $data);
})->name('step-5');

Route::get('/step-6', function () {
    $temp = Temp::latest()->first();
    $payload = json_decode($temp['payload'], true);
    $data = [
        'allTokenizing' => $payload['allTokenizing'],
        'terms' => $payload['terms'],
        'sqrtCs' => $payload['sqrtCs'],
    ];
    return view('cosim.step-6', $data);
})->name('step-6');



Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return Inertia::render('Dashboard');
})->name('dashboard');

resources/views/templates/error.blade.php
    {{-- error validate --}}
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    {{-- error validate --}}

    {{-- ini untuk transaksi error --}}
    @if (\Session::has('alert'))
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-ban"></i> {{ Session::get('alert') }}</h5>
    </div>
    @endif
    {{-- ini untuk transaksi error --}}

    {{-- ini untuk transaksi berhasil --}}
    @if (\Session::has('alert-success'))
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-check"></i> {{ Session::get('alert-success') }}</h5>
    </div>
    @endif
    {{-- ini untuk transaksi berhasil --}}

resources/views/templates/header.blade.php
<head>
    <title>Cosine Similarty - Naskah Khutbah</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

resources/views/templates/navbar.blade.php
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <!-- Brand/logo -->
    <a class="navbar-brand" href="{{ route('cosinesimilarity') }}">Cosine Similarity</a>

    <!-- Links -->
    <ul class="navbar-nav">
        @auth
            <li class="nav-item">
                <a class="nav-link" href="{{ route('cosinesimilarity') }}">Cosine Similarity</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('documents.index') }}">Document</a>
            </li>
            <li class="nav-item">
                <form class="btn btn-sm" action="{{ route('logout') }}" method="post">
                    @method('POST')
                    @csrf
                    <button type="submit"class="btn-sm btn-danger">
                        Logout
                    </button>
                </form>
            </li>
      @endauth
    </ul>
</nav>